### ISSUE TITLE
I can only ask for help after creating a project, is that optimal? [ACD-755]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#246]
Migrated from issue: [ACD-755](https://10clouds.atlassian.net/browse/ACD-755) (Task)

[ACD-755]: https://10clouds.atlassian.net/browse/ACD-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kilodilo** [comment]
Instead of adding something like onboarding tooltips we can't do much more now.
Currently the first screen shows user the message "Create your first project" - it is easy to understand that this is the first step in his journey.
Than the screen shows the user the info about the project and it offers him help with "Guide me" button where he can get to know much more about AIConsole.

So we have now two onboarding elements on the beginning of user's journey:
1. Create your first project button
2. Guide me button

From my perspective, the next step would be preparing tooltip onboarding with tooltips sharing short information aby the most important elements of our UI.

**Comment by cielecki** [comment]
@kilodilo OK, let's leave it inside the project, I will create a separate ticket for tooltips
