### ISSUE TITLE
[BACKEND] Backend update for Recent Projects [ACD-883]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#378]
Migrated from issue: [ACD-883](https://10clouds.atlassian.net/browse/ACD-883) (Task)

Needed data:,Stats:,materials count (divided on types of materials), chats count, agents with avatars, agents count,Tracking field: to track if user hide his project on recent projects page,Rename feature,Duplicate: ? 

[ACD-883]: https://10clouds.atlassian.net/browse/ACD-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kilodilo** [comment]
The design is here: https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=412%3A3125&mode=design&t=xpRuq7zXGtgCdhYa-1

**Comment by pbaranski9411** [comment]
Backend is done. Needs to be updated on frontend side

FYI @pwksn @AGasior @jakubbilko

**Comment by AGasior** [comment]
@pbaranski9411 Can you update avatars, because now we have only on image

![Zrzut ekranu 2024-01-16 o 10 56 53](https://github.com/10clouds/aiconsole/assets/102804214/730107e5-f1ac-4654-9208-a94408fa5244)

![Zrzut ekranu 2024-01-16 o 10 56 50](https://github.com/10clouds/aiconsole/assets/102804214/5531dcbd-3c45-4fc6-bef4-c1d02763624e)

![avatar-1](https://github.com/10clouds/aiconsole/assets/102804214/8a26cafd-15c5-4a71-939c-a49cfe13679b)

![avatar-2](https://github.com/10clouds/aiconsole/assets/102804214/d820da27-2133-4099-b241-6b7b065c6402)

**Comment by kilodilo** [comment]
I will send them to you ASAP - I haven't got an access to midjourney but Ill try to make avatars with the other tool.

**Comment by AGasior** [comment]
We have separate task for update avatars [550](https://github.com/10clouds/aiconsole/issues/550)
