### ISSUE TITLE
Analysis has been experimentally readded to messages, but it is not styled properly, how it should look like?

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#503]

**Comment by kilodilo** [comment]
![ds](https://github.com/10clouds/aiconsole/assets/152965457/fe8fd1ff-6332-4152-bd55-ec36913f4f14)

Do you mean it should be included in the message like this? :)

**Comment by cielecki** [comment]
Yes!

Few notes:
* This will always be the first thing in a given message group (section with the avatar) and there won't be subsequent analysis sections within a given group.
* Currently analysis is hidden after real message starts generating but it would be nice if it could be accessed by the user
* Flow of the messages and filling in the details of the message (agent, materials) etc should be included in the design. How this looks like without any info when the analysis starts, what happens when it continues etc - best if you would look how the interaction looks like on the current code.

**Comment by kilodilo** [comment]
Ok, I did it here. https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2868%3A13873&mode=design&t=sYQN5C8KAaarWcex-1
but I'm not sure what do you mean in the first point

![Analysis process](https://github.com/10clouds/aiconsole/assets/152965457/bf5bebab-033e-4acc-940e-e1cbdf31ca54)

**Comment by kilodilo** [comment]
@AGasior I've checked how it works in the newest prereleased version and decided to move the analysis process label to the top of the AI message box because it shows before the answer is generated. 
It slightly changed in the terms of the position in the message box, thats all:
![Analysis process](https://github.com/10clouds/aiconsole/assets/152965457/e84fad64-63e6-42e7-8144-a927777bad5f)


I have also added notes to the element that were changed in the Chat options section, we need to remember that it should be done :)
![image](https://github.com/10clouds/aiconsole/assets/152965457/dd11e6d2-f984-41ba-8c1f-86dd0f6a2751)
If you can't do this on your own I can move it to the different issue and assign to the Jakub Bilko for e.g.

**Comment by AGasior** [comment]
@kilodilo Can you create separate issue for "Chat options section" Because it will need also logic part to implement, so it will be cleaner if we have it separate :)

**Comment by kilodilo** [comment]
Ok, done :) I deleted the part about it from the comment above to not mess :)

**Comment by cielecki** [comment]
The current implementation on main was quite obstructive I changed it to: 
![image](https://github.com/10clouds/aiconsole/assets/101296/ff88356c-ab39-4bf1-83b3-20ec753c117b)
![image](https://github.com/10clouds/aiconsole/assets/101296/412e974c-9e5a-4b39-9c16-d4d3601528c8)

and committed it to main, please review both the code @AGasior and design @kilodilo 

The commit for this is here: https://github.com/10clouds/aiconsole/commit/6c25d942cec3dc031c9103d06714e25519df4b92

**Comment by kilodilo** [comment]
same here, let's close this issue.
New chat elements orientation to vertical will impact the analysis
