### ISSUE TITLE
Fix issues with FileObserver failing in test environment

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#624]

**Comment by arudzinska** [comment]
@cielecki what do you exactly mean by "test environment" and at what point does the FileObserver fail? How can I reproduce this bug? 

If it's just a regular pytest run of the test from a related issue, #625, then I'm currently on the `main` branch and it seems to be working (when ran with `poetry run pytest aiconsole/acceptance_tests.py --verbose`):

![image](https://github.com/10clouds/aiconsole/assets/34197094/7fb7de79-44c5-4c13-b1e2-fe91e1d89899)

**Comment by aga-gasinska** [comment]
look into global settings path

**Comment by arudzinska** [comment]
At the moment of giving away this issue my findings are: `test_should_be_able_to_add_new_project` does not create a `.config/` directory with `settings.toml` file in it. The test passes locally, as we have our projects already setup and we've run the Console at least once (so the directory with contents is already there). In GitHub Actions on the other hand, the environment is freshly built from scratch, so the test fails not being able to locate proper files. 

To add some more information, GitHub Actions use `ubuntu-latest` (see `.github/workflows/run-backend-checks.yml` file) - the same system that I used for my tests, so the expected directory and `settings.toml` theoretically should be placed the same way in the user's home directory. I was testing various listing, search-for-file and similar commands in the GitHub workflow to check if the file is located elsewhere, but it wasn't found anywhere on the runner machine.

A proposed solution for this is to add the step of creating `.config/` directory with `settings.toml` file in it or mock it somehow in the tests. At the moment of writing this I'm not sure what is better, because I don't know the app well enough and it's not clear for me what can be mocked and what needs to stay real and run real code.
