### ISSUE TITLE
Fix the open state of the chat settings panel

### ISSUE THREAD

**Issue by jakubbilko** [10clouds/aiconsole#653]
## Expected Behavior

The chat settings panel should remember the open state, currently it defaults to `true` which makes the panel open when switching tabs.

## Actual Behavior

The chat settings panel should remember the open state, we can probably store that in the store.

**Comment by aga-gasinska** [comment]
I need steps to reproduce to be able to check it

**Comment by pwksn** [comment]
@aga-gasinska this issue was about storing the state of the chat options (open / closed). Previously, the chat options were being set to open every time user entered the chat, now the app stores the state of it, so that the user can close the options' dropdown and it will stay closed. Let me know if you need further explanation.

**Comment by aga-gasinska** [comment]
works fine
